apiVersion: kaptain.org/1.11
kind: kubernetes-bundle-vendor-helm-rendered
metadata:
  description: "Vendored Envoy Gateway helm chart rendered to plain kubernetes manifests"

spec:
  layers:
    - layer-github-flow-strict:[1.3,2.0)
  main:
    vendorHelmRendered:
      ociChart: 'oci://docker.io/envoyproxy/gateway-helm'
      moveFiles:
        - source: 'templates/certgen-rbac-0.yaml'
          destination: 'serviceaccount-certgen.yaml'
        - source: 'templates/certgen-rbac-1.yaml'
          destination: 'clusterrole-certgen.yaml'
        - source: 'templates/certgen-rbac-2.yaml'
          destination: 'clusterrolebinding-certgen.yaml'
        - source: 'templates/certgen.yaml'
          destination: 'job-certgen.yaml'
        - source: 'templates/envoy-gateway-config.yaml'
          destination: 'configmap-envoy-gateway-config.yaml'
        - source: 'templates/envoy-gateway-deployment.yaml'
          destination: 'deployment-envoy-gateway.yaml'
        - source: 'templates/envoy-gateway-rbac-0.yaml'
          destination: 'clusterrole-envoy-gateway.yaml'
        - source: 'templates/envoy-gateway-rbac-1.yaml'
          destination: 'clusterrolebinding-envoy-gateway.yaml'
        - source: 'templates/envoy-gateway-service.yaml'
          destination: 'service-envoy-gateway.yaml'
        - source: 'templates/envoy-gateway-serviceaccount.yaml'
          destination: 'serviceaccount-envoy-gateway.yaml'
        - source: 'templates/infra-manager-rbac-0.yaml'
          destination: 'role-infra-manager.yaml'
        - source: 'templates/infra-manager-rbac-1.yaml'
          destination: 'rolebinding-infra-manager.yaml'
        - source: 'templates/leader-election-rbac-0.yaml'
          destination: 'role-leader-election.yaml'
        - source: 'templates/leader-election-rbac-1.yaml'
          destination: 'rolebinding-leader-election.yaml'
        - source: 'templates/certgen-rbac-3.yaml'
          destination: 'role-certgen.yaml'
        - source: 'templates/certgen-rbac-4.yaml'
          destination: 'rolebinding-certgen.yaml'
        - source: 'templates/envoy-proxy-topology-injector-webhook.yaml'
          destination: 'mutatingwebhookconfiguration-topology-injector.yaml'
      sedReplace:
        perFile:
          - file: 'configmap-envoy-gateway-config.yaml'
            patterns:
              - 's|gateway.envoyproxy.io/gatewayclass-controller|gateway.envoyproxy.io/${Environment}-gatewayclass-controller|'
              - 's|^      type: Kubernetes$|      type: Kubernetes\n      watch:\n        type: Namespaces\n        namespaces: [${VendorEnvoyGateway/MonitoredNamespaceList}]|'
              - 's|^      kubernetes:$|      kubernetes:\n        deploy:\n          type: GatewayNamespace|'
      yqTransform:
        perFile:
          - file: 'clusterrole-certgen.yaml'
            expressions:
              - '.metadata.name |= sub(":\$\{Environment\}$", "")'
              - '.metadata.name = "${Environment}:" + .metadata.name'
          - file: 'clusterrole-envoy-gateway.yaml'
            expressions:
              - '.metadata.name |= sub("-role$", "")'
              - '.metadata.name = "${Environment}:" + .metadata.name'
          - file: 'clusterrolebinding-certgen.yaml'
            expressions:
              - '.metadata.name |= sub(":\$\{Environment\}$", "")'
              - '.roleRef.name |= sub(":\$\{Environment\}$", "")'
              - '.metadata.name = "${Environment}:" + .metadata.name'
              - '.roleRef.name = "${Environment}:" + .roleRef.name'
          - file: 'deployment-envoy-gateway.yaml'
            expressions:
              - '.metadata.name = "vendor-" + .metadata.name'
          - file: 'job-certgen.yaml'
            expressions:
              - '.metadata.name = .metadata.name + "-${VersionDnsSafe}"'
              - 'del(.spec.ttlSecondsAfterFinished)'
          - file: 'mutatingwebhookconfiguration-topology-injector.yaml'
            expressions:
              - '.webhooks[0].namespaceSelector = {"matchExpressions": [{"key": "kubernetes.io/metadata.name", "operator": "In", "values": ["KAPTAIN_NAMESPACES_PLACEHOLDER"]}]} | .webhooks[0].namespaceSelector.matchExpressions[0].values style = "flow"'
          - file: 'clusterrolebinding-envoy-gateway.yaml'
            expressions:
              - '.metadata.name |= sub("-rolebinding$", "")'
              - '.roleRef.name |= sub("-role$", "")'
              - '.metadata.name = "${Environment}:" + .metadata.name'
              - '.roleRef.name = "${Environment}:" + .roleRef.name'
      imageRetags:
        - sourceImageUri: 'docker.io/envoyproxy/gateway:v1.7.1'
          tagSuffix: 'gateway'
        - sourceImageUri: 'docker.io/envoyproxy/ratelimit:c8765e89'
          tagSuffix: 'ratelimit'
    hooks:
      prePackagePrepare: .github/bin/pre-package-prepare.bash
  global:
    release:
      versioning:
        maxParts: '4'
        strategy: file-pattern-match
        patternType: custom
        source:
          subPath: src/config
          fileName: VendorHelmRenderedVersion
          pattern: '^v?([0-9]+\.[0-9]+\.[0-9]+)$'
          prefixParts: '3'
