# Source: gateway-helm/templates/envoy-gateway-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ${Environment}:vendor-envoy-gateway-envoy-gateway
  labels:
    kaptain.org/environment: ${Environment}
    app.kubernetes.io/managed-by: Kaptain
    app.kubernetes.io/version: ${Version}
  annotations:
    kaptain.org/environment: ${Environment}
    app.kubernetes.io/managed-by: Kaptain
    app.kubernetes.io/version: ${Version}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ${Environment}:vendor-envoy-gateway-envoy-gateway
subjects:
  - kind: ServiceAccount
    name: 'envoy-gateway'
    namespace: '${Environment}'
