# Source: gateway-helm/templates/leader-election-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vendor-envoy-gateway-gateway-helm-leader-election-rolebinding
  namespace: '${Environment}'
  labels:
    helm.sh/chart: gateway-helm-v1.3.0
    app.kubernetes.io/name: gateway-helm
    app.kubernetes.io/instance: vendor-envoy-gateway
    app.kubernetes.io/version: "${Version}"
    app.kubernetes.io/managed-by: Kaptain
    kaptain.org/environment: ${Environment}
  annotations:
    kaptain.org/environment: ${Environment}
    app.kubernetes.io/managed-by: Kaptain
    app.kubernetes.io/version: ${Version}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: 'vendor-envoy-gateway-gateway-helm-leader-election-role'
subjects:
  - kind: ServiceAccount
    name: 'envoy-gateway'
    namespace: '${Environment}'
