# Source: gateway-helm/templates/certgen-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vendor-envoy-gateway-certgen
  namespace: '${Environment}'
  labels:
    helm.sh/chart: gateway-helm-1.7.1
    app.kubernetes.io/name: gateway-helm
    app.kubernetes.io/instance: vendor-envoy-gateway
    app.kubernetes.io/version: "${Version}"
    app.kubernetes.io/managed-by: Kaptain
    kaptain.org/environment: ${Environment}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "-1" # Ensure rbac is created before the certgen job when using ArgoCD.
    kaptain.org/environment: ${Environment}
    app.kubernetes.io/managed-by: Kaptain
    app.kubernetes.io/version: ${Version}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: 'vendor-envoy-gateway-certgen'
subjects:
  - kind: ServiceAccount
    name: 'vendor-envoy-gateway-certgen'
    namespace: '${Environment}'
