# Source: gateway-helm/templates/envoy-gateway-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: envoy-gateway
  namespace: '${Environment}'
  labels:
    helm.sh/chart: gateway-helm-1.7.1
    app.kubernetes.io/name: gateway-helm
    app.kubernetes.io/instance: vendor-envoy-gateway
    app.kubernetes.io/version: "${Version}"
    app.kubernetes.io/managed-by: Kaptain
    kaptain.org/environment: ${Environment}
  annotations:
    kaptain.org/environment: ${Environment}
    app.kubernetes.io/managed-by: Kaptain
    app.kubernetes.io/version: ${Version}
