name: Kubernetes App - Helm Rendered

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: kube-kaptain/buildon-github-actions/.github/workflows/kubernetes-bundle-vendor-helm-rendered.yaml@dns-friendly-versions-and-strip-prefix
    permissions:
      contents: write
      packages: write
      checks: write
